---
title: "p8105_hw6_yw4199"
author: "Yaduo Wang"
date: "2023-11-29"
output: github_document
---
```{r}
library(tidyverse)
library(modelr)
library(mgcv)
```

## Problem 2
```{r}
# download the data
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

## Problem 3
```{r}
#Load and clean the data for regression analysis.
birthweight <- read.csv("DATA/birthweight.csv")
birthweight = 
  birthweight |> 
  mutate(
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    malform = as.factor(malform),
    mrace = as.factor(mrace)
  )
#check for missing data
colSums(is.na(birthweight))
```

```{r}
fit_all = lm(bwt ~., data = birthweight)
summary(fit_all)
```

```{r}
fit_selected = lm(bwt ~ babysex + bhead + 
                    blength + delwt + gaweeks +
                    smoken, 
                  data = birthweight)
summary(fit_selected)
```

```{r}
# plot of model residuals against fitted values
birthweight |> 
  modelr::add_residuals(fit_selected) |> 
  modelr::add_predictions(fit_selected) |> 
  ggplot(aes(x = pred, y=resid)) + 
  geom_point(alpha = 0.5) + 
  geom_hline(yintercept = 0) +
  labs(x = "Fitted values", y = "Residuals", 
       title = "Model Residuals vs. Fitted Values")
```

```{r}
# cross validation between two models 
cv_df =crossv_mc(birthweight, 100)
cv_df = 
  cv_df |> 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
cv_df = 
  cv_df |> 
  mutate(
    my_model = map(train, \(df) lm(bwt ~ babysex + bhead + 
                  blength + delwt + gaweeks + smoken, data = df)),
    main_effect_mod  = map(train, \(df) lm(bwt ~ blength + gaweeks, data = df)),
    interaction_mod     = map(train, \(df) lm(bwt ~ bhead + blength + babysex + 
                                        bhead*blength +
                                        bhead*babysex +
                                        blength*babysex +
                                        bhead * blength * babysex, data = df))
   ) |> 
  mutate(
    rmse_my = map2_dbl(my_model, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_main = map2_dbl(main_effect_mod, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_interaction = map2_dbl(interaction_mod, test, \(mod, df) rmse(model = mod, data = df)))
```

```{r}
# compare the distribution of RMSE in plots
cv_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") |> 
  mutate(model = fct_inorder(model)) |> 
  ggplot(aes(x = model, y = rmse)) + geom_violin() + theme_bw() + 
  labs(x = "Model", y = "RMSE", 
       title = "Models vs. RMSE")
  
```

